### ISSUE TITLE
Bug: cartesian velocity not exposed in Python

### ISSUE THREAD

**Issue by martiabr** [SINTEFMedtek/libromocc#9]
There is a bug in with operational_velocity in robot.py, it returns the position and rotation vector instead of the velocity.

 Furthermore, get_state().get_operational_velocity() returns the position part of the velocity vector in m/s. I am not sure if this is intended behaviour or not, but elsewhere in the python interface mms are used.

**Comment by androst** [comment]
Thanks. Should be correct in updated version.
